"""Add last_seen column to users table

Revision ID: 284293c1f25b
Revises: 5bf564c4d105
Create Date: 2025-01-10 00:11:25.066183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284293c1f25b'
down_revision = '5bf564c4d105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
