"""Add user_id to TalkootParticipants

Revision ID: 50047b8b4933
Revises: b41acc2d9d3b
Create Date: 2025-01-21 00:08:38.009720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50047b8b4933'
down_revision = 'b41acc2d9d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talkoot_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talkoot_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
