"""Add area and year_of_completion columns to housing_companies table

Revision ID: a45997088485
Revises: 70143ed429c7
Create Date: 2025-01-14 11:58:32.696353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45997088485'
down_revision = '70143ed429c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housing_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_of_completion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housing_companies', schema=None) as batch_op:
        batch_op.drop_column('year_of_completion')
        batch_op.drop_column('area')

    # ### end Alembic commands ###
