"""Lisätty Kokous kategoria

Revision ID: a8c3f26f008f
Revises: f17bc35097cd
Create Date: 2025-01-13 20:30:41.360125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8c3f26f008f'
down_revision = 'f17bc35097cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('Kunnossapito', 'Hoito', 'Parannustoimi', 'Kokous'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('Kunnossapito', 'Hoito', 'Parannustoimi', 'Kokous'),
               nullable=True)

    # ### end Alembic commands ###
