"""Päivitetty taulu

Revision ID: f17bc35097cd
Revises: 643b7e6587d0
Create Date: 2025-01-13 20:07:57.980964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17bc35097cd'
down_revision = '643b7e6587d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'delegated', 'in_progress', 'resolved', 'closed', 'rejected'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault_reports', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'approved', 'delegated', 'in_progress', 'resolved', 'closed', 'rejected'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###
